### PR TITLE
Upgrade to linkerd 1.0.0

### PR DESCRIPTION
**Pull request by aschepis**

### CODE REVIEW

**Review by olix0r — APPROVED** [review]
thanks, @aschepis! lgtm

**Review by klingerf — APPROVED** [review]
⭐️  Great, thanks for putting this together @aschepis. Tested and it's working as expected for me.

**Comment by codefromthecrypt** [comment]
Need to work on marketing :) whats awesome about linkerd 1? Have a link?


Yes pun intended

**Comment by klingerf** [comment]
Hey @adriancole -- checkout https://blog.buoyant.io/2017/04/25/announcing-linkerd-1.0/ for more info. Full release details are here: https://github.com/linkerd/linkerd/releases/tag/1.0.0

**Comment by codefromthecrypt** [comment]
Cool I like some of the naming changes. More intuitive

**Comment by wmorgan** [comment]
@adriancole adding you to our marketing spam list 😄  😄  😄

**Comment by codefromthecrypt** [comment]
Haha

**Pull request merged**
