### PR TITLE
Update dependencies to match Finagle 6.44.0 upgrade in linkerd/linkerd.

### PR DESCRIPTION
**Pull request by moderation**
Tested against linkerd master and confirmed that spans were being sent as expected.

### CODE REVIEW

**Comment by codefromthecrypt** [comment]
looks good. please ping an issue on zipkin-finagle if a future release of finagle doesn't work with zipkin-finagle (scala 2.11). We can do a one-off for 2.11 as needed eventhough we are moving forward with 2.12

**Comment by moderation** [comment]
@adleong is working on Scala 2.12 support for linkerd [now](https://github.com/linkerd/linkerd/tree/alex/scala-2.12). I was planning on another PR for zipkin-finagle 0.4.0 when that lands (although I'm not sure if language version needs to match with the linkerd plugin system).

**Comment by klingerf** [comment]
Thanks for putting this together @moderation! Looks good, but I'd like to hold off on merging until we have published artifacts that include linkerd's Finagle upgrade (linkerd/linkerd@2d8133ada7b78927fad3f020cd2936e680eb10ce). There should be a linkerd 1.0.1 release coming soon, at which point we can bump the linkerd dependency in this repo to 1.0.1, and merge this change.

**Comment by klingerf** [comment]
Good news! linkerd/linkerd@00dfa7fc5db5f4f4983771a34ced718417b1e2f5 just merged, which moves linkerd to scala 2.12. So once the new artifacts are available as part of a linkerd release, you'll also be able to update the finagle-zipkin dependency in this branch to 0.4.0.

**Comment by moderation** [comment]
@klingerf In order to complete the change we need to have a Scala 2.12 version of telemetry-core in the Maven repos https://mvnrepository.com/artifact/io.buoyant/telemetry-core_2.11. /cc @adriancole

**Comment by klingerf** [comment]
@moderation That's correct. We won't start publishing 2.12 artifacts until the next linkerd release (which is also when we'll be moving linkerd to finagle 6.44.0). So I think it makes sense to hold off on merging this branch until the next release happens, at which point we can move this repo to scala 2.12, finagle 6.44.0, and zipkin-finagle 0.4.0.

**Comment by moderation** [comment]
@klingerf I've added a new [commit](https://github.com/linkerd/linkerd-zipkin/pull/8/commits/1d583815c2bd6b6a232737e559e48a61d19773bf) that updated linkerd to 1.0.2, zipkin-finagle to 0.4.0 and Scala to 2.12.1. /cc @adriancole

**Review by klingerf — APPROVED** [review]
⭐️  Great, thanks for updating.

**Pull request merged**
